### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by felixrabe** [hydrogen18/stoppableListener#4]
Probably along the lines of
- start listener (localhost:0)
- connect to it -> success
- stop listener
- connect to it -> failure

**Comment by hezhixiong** [comment]
(1)start listener (localhost:8080)
(2)access address(localhost:8080) -> success(output:Hello HTTP!) 
(3)stop listener
(4)access address(localhost:8080) -> success(output:Hello HTTP!)  is this a bug?
I think,the address(localhost:8080) is not allowed to access in the step(4).

**Comment by hydrogen18** [comment]
@hezhixiong I am unsure what you mean by this comment.

**Comment by tjmerritt** [comment]
I think the issue is that the while the listener thread gets stopped.  The threads for individual connections do not get stopped.  So after the listener is successfully, stopped at step (3), the connection created at step (2) still persists and the thread servicing it is able to respond at step (4), even though the expectation is that the server has already stopped.  This can only happen if the client that is connecting keeps the connection alive after the first request, which most good clients will do.

**Comment by hydrogen18** [comment]
This issue has been open for 2 years and no one has contributed tests. If anyone would like to, please open a pull request.
